# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end



# Helper methods for all objects: 

def new_parser_with_data
	doc = load_sample_xml
	parser = GreenButton::Parser.new(doc)
end

def load_and_parse_greenbutton
	parser = new_parser_with_data
	parser.parse_greenbutton_xml
end

def load_sample_xml
	file_path = "data/Coastal_Single_Family_Jan_1_2011_to_Jan_1_2012.xml"	
	loader = GreenButton::Loader.new
	loader.load_xml_from_file(file_path)
end